name: 🐛 Bug Report
description: File a bug report
labels: ["Status: Awaiting triage"]
body:
  - type: markdown
    attributes:
      value: >
        ### ⚠️ Please remember: issues are for *bugs* only!

  - type: markdown
    attributes:
      value: |
        #### Unsure? Have a questions? 👉 [Start a new discussion](https://github.com/ESP32Async/ESPAsyncWebServer/discussions/new)

        #### Before opening a new issue, please make sure you have searched:

        - In the [documentation](https://github.com/ESP32Async/ESPAsyncWebServer)
        - In the [discussions](https://github.com/ESP32Async/ESPAsyncWebServer/discussions)
        - In the [issues](https://github.com/ESP32Async/ESPAsyncWebServer/issues)
        - In the [examples](https://github.com/ESP32Async/ESPAsyncWebServer/tree/main/examples)

        #### Make sure you are using:

        - The [latest version of ESPAsyncWebServer](https://github.com/ESP32Async/ESPAsyncWebServer/releases)
        - The [latest version of AsyncTCP](https://github.com/ESP32Async/AsyncTCP/releases) (for ESP32)

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - ESP32
        - ESP8266
        - RP2040
    validations:
      required: true

  - type: dropdown
    id: tooling
    attributes:
      label: IDE / Tooling
      options:
        - Arduino (IDE/CLI)
        - pioarduino
        - ESP-IDF
        - PlatformIO
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the issue.
      placeholder: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: stack-trace
    attributes:
      label: Stack Trace
      description: Please provide a debug message or error message. If you have a Guru Meditation Error or Backtrace, [please decode it](https://maximeborges.github.io/esp-stacktrace-decoder/).
      placeholder: For Arduino IDE, Enable Core debug level - Debug on tools menu, then put the serial output here.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Minimal Reproductible Example (MRE)
      description: Post the code or the steps to reproduce the issue.
      placeholder: Post the code or the steps to reproduce the issue.
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "I confirm that:"
      options:
        - label: I have read the documentation.
          required: true
        - label: I have searched for similar discussions.
          required: true
        - label: I have searched for similar issues.
          required: true
        - label: I have looked at the examples.
          required: true
        - label: I have upgraded to the lasted version of ESPAsyncWebServer (and AsyncTCP for ESP32).
          required: true
